### ISSUE TITLE
Problem with password 

### ISSUE THREAD

**Issue by pasqual1no** [Klangen82/Creality-Control#5]
I am asked to enter the 3D printer password but I have not set any password. I can not go on.

**Comment by fedepag76** [comment]
I have the same problem!!!

**Comment by k3ntinhu** [comment]
same problem here.

**Comment by fastender** [comment]
What is the password?

**Comment by Akilarounet** [comment]
No password on my K1 Max, any idea ?

**Comment by fastender** [comment]
Found another solution over Moonraker, its compatible with Ender 3v3

**Comment by inakiarredondo** [comment]
@Klangen82 please let us know if you have any plan to solve the password issue or it would be better to find a different solution, as @fastender is proposing. The integration looks great, but with this issue it is unusable. Thank you.

**Comment by Klangen82** [comment]
Hello everyone,

I haven't had the time to fully work on this, but since it's an open-source project, you're all welcome to contribute! I've made an updated version available at https://github.com/Klangen82/Creality-Control/tree/Next-release where the WiFi Box doesn't require a password at all. Unfortunately, I haven't been able to test it (as I only have one printer Halot One resin printer), and the WiFi Box uses HTTP instead of WebSocket, so I'm unsure if it will work as expected. I'm also not certain if the sensors will function correctly. Please feel free to test it out, provide feedback, or modify the code to make it work. Have fun experimenting!

**Comment by inakiarredondo** [comment]
Hello Martin.

Thanks a lot for your super-quick answer!!
Sure, here you are:
- Just tried the updated version, choosing the "wifi_box" option, and I get the "Failed to connect to the printer, check your input and try again. Printer needs to be online to be able to be added." message.
- I have an Ender 3 S1, with wifi box. 
- Indeed, before and after testing the update I I double-checked I can access the printer using the Creality app with no problem.

**Comment by Klangen82** [comment]
Cool! Could you please provide the logs from HA? I only need the ones created by this integration. Go to Settings > System > Logs, search for ‘Creality,’ then load the full logs and copy-paste them here.

**Comment by inakiarredondo** [comment]
Just did it. But there are no traces in HA logs. However, then I tried using a wrong IP address... and the form takes a bit longer to refresh and show the error message than when I use the right IP address (which produces an immediate response). Could it means the integration can reach the wifi-box but then something occurs that is not reflected in the logs?

**Comment by pcartwright81** [comment]
Currently looking into this.  I was able to make it set up by putting in the IP address and port 81, but I think it took 3x to get it to show up properly.  I am missing the buttons, and should be able to fix that after I finish with another integration.

2 logs I see are
Connection:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 351, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 398, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 501, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/creality_control/config_flow.py", line 27, in async_step_user
    user_input["host"], user_input["port"], user_input["password"]
                                            ~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'password'


Buttons

Error while setting up creality_control platform for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/creality_control/button.py", line 20, in async_setup_entry
    CrealityControlButton(coordinator, f"{coordinator.config['model']} Pause Print", "PRINT_PAUSE"),
                                          ~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'model'

**Comment by jrspowers** [comment]
hallo,
i´m trying to load the integration , but i keep getting this erro . i have the correct ip adress, and the password is the one from creality cloud , right ? 
![Schermafbeelding 2024-11-13 142202](https://github.com/user-attachments/assets/bc933c04-12e7-415b-bada-b1cbb01dc910)

**Comment by stoffies00711** [comment]
I managed to load the entities using port 9999 and Creality_2023 as the password but they're all unavailable.

Creality K1C (has built in WiFi)
not resin but looking for some integration into HA

![image](https://github.com/user-attachments/assets/3ce1d02a-0ba8-407e-b29a-4fe1aba98931)

**Comment by pcartwright81** [comment]
Please post the following:
Type of printer.
Whether or not you have a creality wifi box or the printer has a network adapter built in.

**Comment by stoffies00711** [comment]
Sorry.  Added it to the post above

**Comment by pcartwright81** [comment]
It looks like you are not using the custom K1C files from https://github.com/Klangen82/Creality-Control/issues/1

**Comment by sfrsfrsfrsfr** [comment]
Hi, looks like Creality K2 Plus works on 9999 port and default pass Creality_2023. (via wifi)
Connection is successful but unfortunately every sensor is in unknown status.

**Comment by pcartwright81** [comment]
Any idea if it is web socket or rest?  You could try the K1C files.

**Comment by pcartwright81** [comment]
@stoffies00711 Did you try the custom files?  I have some ideas for supporting other models.

**Comment by stoffies00711** [comment]
@pcartwright81 Hey there.  I pretty new at this and not a developer.  I used my mikrotik router to see which ports were being accessed and then came across port 9999 and the mqtt ports.  Just thought I'd mention the port.  I managed to pull the camera stream into my home assistant but that's it.

**Comment by pcartwright81** [comment]
Ok #1 has files that can be downloaded for K1C.  Replace those files and the K1C should work.  https://github.com/user-attachments/files/15532806/custom_files_for_K1C.zip

**Comment by stoffies00711** [comment]
I will check it out thank you

**Comment by stoffies00711** [comment]
It works.
Now I just need to somehow create templates so that the times show more 'user friendly'.
Thanks
![image](https://github.com/user-attachments/assets/5d9186c9-ab6e-41eb-a694-c805e75f0321)

**Comment by sushiguy35** [comment]
I've got an ender 3 v3 which i got working with pass Creality_2023 and port 9999, but all entities are unknown, why is this and how can i fix?

**Comment by pcartwright81** [comment]
V3 SE with wifi box?

**Comment by Davvy80** [comment]
Hi, I have a Creality K1 Max model, with the printer's IP, port 9999, and password Creality_2023. I can access it, but the entities are unknown. My router is a Fritz!box 7590 Ax. Do you have any suggestions for me?"

**Comment by pcartwright81** [comment]
Did you look at https://github.com/Klangen82/Creality-Control/issues/1?

**Comment by Davvy80** [comment]
> Did you look at #1?
You're very welcome, I solved it with your advice.
I'll return the favor.

**Comment by gaspe80** [comment]
Thank you for the great work, I have integrated a Creality CR 10 SE. I noticed that the Pause/Resume Print and Stop Print buttons don't seem to work, and it doesn't seem to detect the print progress and the current layer. Unfortunately, I don't know where to start to try to help, but thanks anyway

![Image](https://github.com/user-attachments/assets/f517dca2-a173-463b-80e0-59ff0f6576b2)

![Image](https://github.com/user-attachments/assets/b55a1976-be56-40bb-a770-274e78a9a075)

**Comment by n0S3curity** [comment]
> Ok [#1](https://github.com/Klangen82/Creality-Control/issues/1) has files that can be downloaded for K1C. Replace those files and the K1C should work. https://github.com/user-attachments/files/15532806/custom_files_for_K1C.zip

what did you changed for k1C?
i have Ender V3-KE and i see the following:

![Image](https://github.com/user-attachments/assets/082c2314-6c59-4798-a170-18fcd088d691)

**Comment by heatvent** [comment]
I have the K1 SE and I tried setting up using the custom K1C files. I used port 9999 and the Creality_2023 password. I first got an error about using hass.config_entries.async_forward_entry_setup rather than hass.config_entries.async_forward_entry_setups in the init.py file. I changed to setups and the integration seems to load fine. However, I can't find any devices or entities that have anything to do with it?? Where should I be able to find these or maybe I am missing something.

I did find a couple of module errors in the log???

ModuleNotFoundError: No module named 'custom_components.creality_control.s'
ModuleNotFoundError: No module named 'custom_components.creality_control.b'

**Comment by miz-online** [comment]
did you get it to run?
I completely removed the integraiton and readded, one in combination of this repo, the extra files and the adoption from legacy setup calls, and once from your fork.
Integration is added, but entity is not.
before I had it all running, after upgrade of HA all states went 'unknown' after fixing the API call, but camera still worked.
Now event the entity and sensors are not shown anymore.
Can't find helpful messages in the logs as well

**Comment by stoffies00711** [comment]
Mine was working fine until the update.  I cannot find the link now but I took a screenshot of it.  I just modified the lines and it worked.

![Image](https://github.com/user-attachments/assets/41e439ff-8306-447e-ba6c-9330447483e9)

**Comment by stoffies00711** [comment]
Mine was good until the update.  Here is the link of how to fix:
https://github.com/Klangen82/Creality-Control/issues/13
