### ISSUE TITLE
Next Release Wifi Box Buttons Error

### ISSUE THREAD

**Issue by pcartwright81** [Klangen82/Creality-Control#6]
Error while setting up creality_control platform for button
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/creality_control/button.py", line 20, in async_setup_entry
CrealityControlButton(coordinator, f"{coordinator.config['model']} Pause Print", "PRINT_PAUSE"),
~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'model'

**Comment by pcartwright81** [comment]
In the setup I added model  vol.Required("model"): cv.string because I was trying to set up for having multiple boxes in ha instance.  However the unique ids are like this  192.168.1.232_print so they are unique already.

**Comment by pcartwright81** [comment]
I rewrote my code in October following the integration template, but it is only for the wifi box.  I have some ideas to merge code, and will start an information gathering post.  https://github.com/pcartwright81/creality_box_control
